# Generated by Django 5.1.5 on 2025-01-28 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_category_options'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberProfile_Private',
            new_name='Member_Data_Private',
        ),
    ]
