# Generated by Django 5.1.5 on 2025-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_memberprofile_private_member_data_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member_data_private',
            options={'ordering': ['default_lastname', 'default_firstname'], 'verbose_name_plural': 'Member_Data_Private'},
        ),
    ]
