# Generated by Django 5.1.5 on 2025-02-15 12:10

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_member_data_private_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_data_private',
            name='default_country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member_data_private',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
