# Generated by Django 5.1.5 on 2025-02-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_member_data_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member_data_private',
            options={'ordering': ['member', 'default_lastname', 'default_firstname'], 'verbose_name_plural': 'Member Data Private'},
        ),
        migrations.AlterModelOptions(
            name='member_data_public',
            options={'ordering': ['member', 'public_lastname', 'public_firstname'], 'verbose_name_plural': 'Member Data Public'},
        ),
    ]
