# Generated by Django 5.1.5 on 2025-02-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_member_data_private_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_data_public',
            name='film_tv_credits',
        ),
    ]
