# Generated by Django 5.1.5 on 2025-02-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_member_data_private_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_data_public',
            name='imdb',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='member_data_public',
            name='public_firstname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='member_data_public',
            name='public_lastname',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='member_data_public',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
