# Generated by Django 3.2.25 on 2025-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('new_member_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('renewal_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'ordering': ['-new_member_price'],
            },
        ),
    ]
