# Generated by Django 3.2.25 on 2025-01-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['new_member_price', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
