# Generated by Django 5.1.5 on 2025-01-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership', '0003_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='membership_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(editable=False, max_length=32)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('membership_purchased', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='membership.category')),
            ],
        ),
    ]
