# Generated by Django 5.1.5 on 2025-01-30 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('membership', '0003_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='membership_purchase',
            new_name='MembershipPurchase',
        ),
    ]
