# Generated by Django 5.1.5 on 2025-01-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_rename_membership_purchase_membershippurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippurchase',
            name='purchase_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
